In [5]:
import cv2 as cv
print(cv.__version__)
#python+OpenCVのプログラミング環境構築 

4.5.1


In [6]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print('足し算\n',a+b)
print('引き算\n',a-b)
print('掛け算\n',a.dot(b))
print('割り算\n',a/b)

足し算
 [[ 6  8]
 [10 12]]
引き算
 [[-4 -4]
 [-4 -4]]
掛け算
 [[19 22]
 [43 50]]
割り算
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
pica = cv.imread('./pic1.jpg')
print(pica.shape)
pica_big = cv.resize(pica,(960,1280))#画像の拡大
pica_small = cv.resize(pica,(96,128))#画像の縮小
x,y = pica.shape[:2] #画像の回転
rotate = cv.getRotationMatrix2D((x/2,y/2),45,0.5) 
pica_rotate = cv.warpAffine(pica,rotate,(x,y))
pica_bin = cv.imread('./pic1.jpg',0)#画像の二値化

# cv.imshow('pica',pica)
# cv.imshow('pica_big',pica_big)
# cv.imshow('pica_small',pica_small)
# cv.imshow('pica_rotate',pica_rotate)
# cv.imshow('pica_bin',pica_bin)
# cv.waitKey(0)
# cv.destroyAllWindows()

(480, 640, 3)


In [8]:
picb = cv.imread('./pic2.jpg')#差分画像作成 
diff = pica - picb
diff = diff.astype(np.uint8)
cv.imwrite('diff.jpg', diff)

True