In [1]:
import cv2 as cv
print(cv.__version__)
#python+OpenCVのプログラミング環境構築 

4.5.1


In [2]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print('足し算\n',a+b)
print('引き算\n',a-b)
print('掛け算\n',a.dot(b))
print('割り算\n',a/b)

足し算
 [[ 6  8]
 [10 12]]
引き算
 [[-4 -4]
 [-4 -4]]
掛け算
 [[19 22]
 [43 50]]
割り算
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [3]:
pica = cv.imread('./pic1.jpg')
print(pica.shape)
pica_big = cv.resize(pica,(960,1280))#画像の拡大
pica_small = cv.resize(pica,(96,128))#画像の縮小
x,y = pica.shape[:2] #画像の回転
rotate = cv.getRotationMatrix2D((x/2,y/2),45,0.5) 
pica_rotate = cv.warpAffine(pica,rotate,(x,y))
pica_bin = cv.imread('./pic1.jpg',0)#画像の二値化

# cv.imshow('pica',pica)
# cv.imshow('pica_big',pica_big)
# cv.imshow('pica_small',pica_small)
# cv.imshow('pica_rotate',pica_rotate)
# cv.imshow('pica_bin',pica_bin)

# cv.imwrite('pica_big.jpg',pica_big)
# cv.imwrite('pica_small.jpg',pica_small)
# cv.imwrite('pica_rotate.jpg',pica_rotate)
# cv.imwrite('pica_bin.jpg',pica_bin)

# cv.waitKey(0)
# cv.destroyAllWindows()

(480, 640, 3)


True

In [4]:
picb = cv.imread('./pic2.jpg')#差分画像作成 
diff = pica - picb
diff = diff.astype(np.uint8)
#cv.imwrite('diff.jpg', diff)

In [5]:
orb = cv.ORB_create()#特徴量の比較
kps = orb.detect(pica_bin)
orb_result = cv.drawKeypoints(pica_bin, kps, None, -1, cv.DrawMatchesFlags_DEFAULT)
# cv.imshow("result", result)
# cv.waitKey(0)
# cv.imwrite('orb_result.jpg', orb_result)

In [6]:
picb_bin = cv.imread('./pic2.jpg',0)
kp1, des1 = orb.detectAndCompute(pica_bin,None)
kp2, des2 = orb.detectAndCompute(picb_bin,None)
bf = cv.BFMatcher(cv.NORM_HAMMING, crossCheck=True)
Brute_Force_matches = bf.match(des1,des2)
Brute_Force_result = cv.drawMatches(pica_bin, kp1, picb_bin, kp2, Brute_Force_matches, None)

#cv.imshow("orb-match", result)
#cv.waitKey(0)
#cv.imwrite('Brute_Force_result.jpg', Brute_Force_result)

In [9]:
bf = cv.BFMatcher(cv.NORM_HAMMING, crossCheck=True)
matches = bf.knnMatch(des1, des2, k=1)

while [] in matches:
    matches.remove([])
matches = sorted(matches, key = lambda x:x[0].distance)

KNN_result = cv.drawMatchesKnn(pica_bin, kp1, picb_bin, kp2, 
                               matches[0:15], None, matchColor = (0,255,0), singlePointColor = (255,0,255))
#cv.imwrite('KNN_result.jpg',KNN_result)

True